# Git工作评估系统配置

# 通用配置
general:
  project_name: "工作评估系统"
  time_range: 7  # 默认查询最近7天的数据
  output_dir: "./reports"

# Git提供者配置
git_providers:
  github:
    token: "your_github_token"  # 请替换为实际的GitHub API令牌
    organization: "your_organization"  # 请替换为实际的组织名称
    repositories:  # 要监控的仓库列表，留空表示监控组织下所有仓库
      - "repo1"
      - "repo2"
  
  # 可以添加其他Git提供者，如GitLab
  # gitlab:
  #   token: "your_gitlab_token"
  #   group: "your_group"
  #   projects: []

# 团队成员配置
team_members:
  - name: "张三"
    email: "zhangsan@example.com"
    username: "zhangsan"
  
  - name: "李四"
    email: "lisi@example.com"
    username: "lisi"
  
  - name: "王五"
    email: "wangwu@example.com"
    username: "wangwu"

# 代理配置
agents:
  llm_provider: "openai"  # 使用的LLM提供者
  model_name: "gpt-4"     # 使用的模型名称
  api_key: "your_openai_api_key"  # 请替换为实际的API密钥

# 报告配置
reports:
  format: "markdown"  # 报告格式：markdown或html
  include_metrics: true  # 是否包含指标
  template_dir: "./config/templates"  # 报告模板目录
  individual_reports: true  # 是否为每个成员生成单独的报告

# MCP服务器配置
server:
  host: "localhost"
  port: 8000
  debug: false
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"